# 开发环境配置

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://152.136.123.201:3306/indie_station?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql_Xdwzfi

  # Redis 配置
  data:
    redis:
      host: 152.136.123.201
      port: 6379
      password: bkcw123456
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Cloudflare R2 配置 (S3 兼容)
r2:
  endpoint: https://cf390a74405dfbb1cfb142150ba069e2.r2.cloudflarestorage.com
  access-key-id: 26e7ff428424e28234ed2b952122baa0
  secret-access-key: 7589d31697f6461be205249bcafc1aec84582b703791f2e017cb6c55259eab77
  bucket: osengroup
  public-url: https://pub-17c3d760aa8d450ab56c3748b44f6cd3.r2.dev